# Generated by Django 5.2 on 2025-04-29 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='el numero debe tener entre 9 y 15 digitos', regex='^\\+?\\d{9,15}$')], verbose_name='Numero de Telefono'),
        ),
    ]
